// Generated by Fair on 2021-06-22 10:33:13.495688.

import 'package:demo/count_widget.dart';
import 'package:flutter/material.dart';
import 'package:fair/fair.dart';
import 'package:fair_version/fair_version.dart';

class AppGeneratedModule extends GeneratedModule {
  @override
  Map<String, dynamic> components() {
    return {
      'Count': (props) => Count(
            key: props['key'],
            count: props['count'],
          ),
    };
  }

  @override
  Map<String, bool> mapping() {
    return const {
      'Count': true,
    };
  }
}
