// GENERATED CODE - DO NOT MODIFY BY HAND

part of services.common_server_api;

// **************************************************************************
// ShelfRouterGenerator
// **************************************************************************

Router _$CommonServerApiRouter(CommonServerApi service) {
  final router = Router();
  router.add(
    'POST',
    r'/service/api/dartservices/<apiVersion>/analyze',
    service.analyze,
  );
  router.add(
    'POST',
    r'/service/api/dartservices/<apiVersion>/compileDDC',
    service.compileDDC,
  );
  router.add(
    'POST',
    r'/service/api/dartservices/<apiVersion>/complete',
    service.complete,
  );
  router.add(
    'POST',
    r'/service/api/dartservices/<apiVersion>/fixes',
    service.fixes,
  );
  router.add(
    'POST',
    r'/service/api/dartservices/<apiVersion>/assists',
    service.assists,
  );
  router.add(
    'POST',
    r'/service/api/dartservices/<apiVersion>/format',
    service.format,
  );
  router.add(
    'POST',
    r'/service/api/dartservices/<apiVersion>/document',
    service.document,
  );
  router.add(
    'POST',
    r'/service/api/dartservices/<apiVersion>/version',
    service.versionPost,
  );
  router.add(
    'GET',
    r'/service/api/dartservices/<apiVersion>/version',
    service.versionGet,
  );
  router.add(
    'POST',
    r'/service/api/dartservices/<apiVersion>/fairCompile',
    service.fairCompile,
  );
  router.add(
    'POST',
    r'/service/api/dartservices/<apiVersion>/fairRun',
    service.fairRun,
  );
  router.add(
    'POST',
    r'/service/api/dartservices/<apiVersion>/getProjects',
    service.getProjects,
  );
  router.add(
    'POST',
    r'/service/api/dartservices/<apiVersion>/getProjectPages',
    service.getProjectPages,
  );
  router.add(
    'POST',
    r'/service/api/dartservices/<apiVersion>/createProjectPage',
    service.createProjectPage,
  );
  router.add(
    'POST',
    r'/service/api/dartservices/<apiVersion>/deleteProjectPage',
    service.deleteProjectPage,
  );
  router.add(
    'POST',
    r'/service/api/dartservices/<apiVersion>/copyProjectPage',
    service.copyProjectPage,
  );
  router.add(
    'POST',
    r'/service/api/dartservices/<apiVersion>/createTemplatePage',
    service.createTemplatePage,
  );
  router.add(
    'POST',
    r'/service/api/dartservices/<apiVersion>/getTemplatePages',
    service.getTemplatePages,
  );
  router.add(
    'POST',
    r'/service/api/dartservices/<apiVersion>/getCustomComponents',
    service.getCustomComponents,
  );
  router.add(
    'POST',
    r'/service/api/dartservices/<apiVersion>/getCustomActions',
    service.getCustomActions,
  );
  router.add(
    'POST',
    r'/service/api/dartservices/<apiVersion>/getDependencyFilePath',
    service.getDependencyFilePath,
  );
  router.add(
    'POST',
    r'/service/api/dartservices/<apiVersion>/changeDependency',
    service.changeDependency,
  );
  router.add(
    'POST',
    r'/service/api/dartservices/<apiVersion>/doPubGet',
    service.doPubGet,
  );
  router.add(
    'POST',
    r'/service/api/dartservices/<apiVersion>/deleteCustomCodeItem',
    service.deleteCustomCodeItem,
  );
  router.add(
    'POST',
    r'/service/api/dartservices/<apiVersion>/createCustomComponent',
    service.createCustomComponent,
  );
  router.add(
    'POST',
    r'/service/api/dartservices/<apiVersion>/createCustomAction',
    service.createCustomAction,
  );
  router.add(
    'POST',
    r'/service/api/dartservices/<apiVersion>/getTemplateProjects',
    service.getTemplateProjects,
  );
  router.add(
    'POST',
    r'/service/api/dartservices/<apiVersion>/createProject',
    service.createProject,
  );
  router.add(
    'POST',
    r'/service/api/dartservices/<apiVersion>/deleteProject',
    service.deleteProject,
  );
  router.add(
    'POST',
    r'/service/api/dartservices/<apiVersion>/getPage',
    service.getPage,
  );
  router.add(
    'POST',
    r'/service/api/dartservices/<apiVersion>/getFairDslList',
    service.getFairDslList,
  );
  router.add(
    'POST',
    r'/service/api/dartservices/<apiVersion>/getFairDsl',
    service.getFairDsl,
  );
  router.add(
    'POST',
    r'/service/api/dartservices/<apiVersion>/getApiCall',
    service.getApiCall,
  );
  router.add(
    'POST',
    r'/service/api/dartservices/<apiVersion>/addApiCall',
    service.addApiCall,
  );
  router.add(
    'POST',
    r'/service/api/dartservices/<apiVersion>/deleteApiCall',
    service.deleteApiCall,
  );
  router.add(
    'POST',
    r'/service/api/dartservices/<apiVersion>/getComponentList',
    service.getComponentList,
  );
  router.add(
    'POST',
    r'/service/api/dartservices/<apiVersion>/exportProject',
    service.exportProject,
  );
  router.add(
    'POST',
    r'/service/api/dartservices/<apiVersion>/getQrCode',
    service.getQrCode,
  );
  router.add(
    'POST',
    r'/service/api/dartservices/<apiVersion>/uploadPlugin',
    service.uploadPlugin,
  );
  return router;
}
