// Generated by Fair on 2021-05-19 19:34:08.774528.
import 'package:flutter_compontent/custom_widget.dart';

import 'package:flutter/material.dart';
import 'package:fair/fair.dart';
import 'package:fair_version/fair_version.dart';

class AppGeneratedModule extends GeneratedModule {
  @override
  Map<String, dynamic> components() {
    return {
      'CustomWidget': (props) => CustomWidget(
            key: props['key'],
            title: props['title'] ?? 'Test',
          ),
    };
  }

  @override
  Map<String, bool> mapping() {
    return const {
      'CustomWidget': true,
    };
  }
}
