// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/assets_generator
// **************************************************************************
// ignore_for_file: constant_identifier_names

class Assets {
  const Assets._();
  static const String
      assets_fair_lib_src_page_list_cells_sample_page_stateful_cell_fair_bin =
      'assets/fair/lib_src_page_list_cells_sample_page_stateful_cell.fair.bin';

  static const String
      assets_fair_lib_src_page_list_cells_sample_page_stateful_cell_fair_js =
      'assets/fair/lib_src_page_list_cells_sample_page_stateful_cell.fair.js';

  static const String
      assets_fair_lib_src_page_list_cells_sample_page_stateful_cell_fair_json =
      'assets/fair/lib_src_page_list_cells_sample_page_stateful_cell.fair.json';

  static const String
      assets_fair_lib_src_page_list_load_more_sample_list_with_logic_fair_bin =
      'assets/fair/lib_src_page_list_load-more_sample_list_with_logic.fair.bin';

  static const String
      assets_fair_lib_src_page_list_load_more_sample_list_with_logic_fair_js =
      'assets/fair/lib_src_page_list_load-more_sample_list_with_logic.fair.js';

  static const String
      assets_fair_lib_src_page_list_load_more_sample_list_with_logic_fair_json =
      'assets/fair/lib_src_page_list_load-more_sample_list_with_logic.fair.json';

  static const String
      assets_fair_lib_src_page_list_load_more_sample_logic_loadmore_page_fair_bin =
      'assets/fair/lib_src_page_list_load-more_sample_logic_loadmore_page.fair.bin';

  static const String
      assets_fair_lib_src_page_list_load_more_sample_logic_loadmore_page_fair_js =
      'assets/fair/lib_src_page_list_load-more_sample_logic_loadmore_page.fair.js';

  static const String
      assets_fair_lib_src_page_list_load_more_sample_logic_loadmore_page_fair_json =
      'assets/fair/lib_src_page_list_load-more_sample_logic_loadmore_page.fair.json';

  static const String
      assets_fair_lib_src_page_list_load_more_sample_logic_loadmore_page_manually_fair_bin =
      'assets/fair/lib_src_page_list_load-more_sample_logic_loadmore_page_manually.fair.bin';

  static const String
      assets_fair_lib_src_page_list_load_more_sample_logic_loadmore_page_manually_fair_js =
      'assets/fair/lib_src_page_list_load-more_sample_logic_loadmore_page_manually.fair.js';

  static const String
      assets_fair_lib_src_page_list_load_more_sample_logic_loadmore_page_manually_fair_json =
      'assets/fair/lib_src_page_list_load-more_sample_logic_loadmore_page_manually.fair.json';

  static const String
      assets_fair_lib_src_page_logic_page2page_sample_logic_page2page_fair_bin =
      'assets/fair/lib_src_page_logic-page2page_sample_logic_page2page.fair.bin';

  static const String
      assets_fair_lib_src_page_logic_page2page_sample_logic_page2page_fair_js =
      'assets/fair/lib_src_page_logic-page2page_sample_logic_page2page.fair.js';

  static const String
      assets_fair_lib_src_page_logic_page2page_sample_logic_page2page_fair_json =
      'assets/fair/lib_src_page_logic-page2page_sample_logic_page2page.fair.json';

  static const String
      assets_fair_lib_src_page_logic_page_sample_logic_page_fair_bin =
      'assets/fair/lib_src_page_logic-page_sample_logic_page.fair.bin';

  static const String
      assets_fair_lib_src_page_logic_page_sample_logic_page_fair_js =
      'assets/fair/lib_src_page_logic-page_sample_logic_page.fair.js';

  static const String
      assets_fair_lib_src_page_logic_page_sample_logic_page_fair_json =
      'assets/fair/lib_src_page_logic-page_sample_logic_page.fair.json';

  static const String
      assets_fair_lib_src_page_plugins_net_pic_net_demo_pic_fair_bin =
      'assets/fair/lib_src_page_plugins_net_pic_net_demo_pic.fair.bin';

  static const String
      assets_fair_lib_src_page_plugins_net_pic_net_demo_pic_fair_js =
      'assets/fair/lib_src_page_plugins_net_pic_net_demo_pic.fair.js';

  static const String
      assets_fair_lib_src_page_plugins_net_pic_net_demo_pic_fair_json =
      'assets/fair/lib_src_page_plugins_net_pic_net_demo_pic.fair.json';

  static const String
      assets_fair_lib_src_page_plugins_net_pic_net_demo_pic2_fair_bin =
      'assets/fair/lib_src_page_plugins_net_pic_net_demo_pic2.fair.bin';

  static const String
      assets_fair_lib_src_page_plugins_net_pic_net_demo_pic2_fair_js =
      'assets/fair/lib_src_page_plugins_net_pic_net_demo_pic2.fair.js';

  static const String
      assets_fair_lib_src_page_plugins_net_pic_net_demo_pic2_fair_json =
      'assets/fair/lib_src_page_plugins_net_pic_net_demo_pic2.fair.json';

  static const String
      assets_fair_lib_src_page_plugins_permission_sample_permission_page_fair_bin =
      'assets/fair/lib_src_page_plugins_permission_sample_permission_page.fair.bin';

  static const String
      assets_fair_lib_src_page_plugins_permission_sample_permission_page_fair_js =
      'assets/fair/lib_src_page_plugins_permission_sample_permission_page.fair.js';

  static const String
      assets_fair_lib_src_page_plugins_permission_sample_permission_page_fair_json =
      'assets/fair/lib_src_page_plugins_permission_sample_permission_page.fair.json';

  static const String assets_fair_lib_src_page_sugars_ifequal_page_fair_bin =
      'assets/fair/lib_src_page_sugars_ifequal_page.fair.bin';

  static const String assets_fair_lib_src_page_sugars_ifequal_page_fair_js =
      'assets/fair/lib_src_page_sugars_ifequal_page.fair.js';

  static const String assets_fair_lib_src_page_sugars_ifequal_page_fair_json =
      'assets/fair/lib_src_page_sugars_ifequal_page.fair.json';

  static const String
      assets_fair_lib_src_page_sugars_ifequalbool_page_fair_bin =
      'assets/fair/lib_src_page_sugars_ifequalbool_page.fair.bin';

  static const String assets_fair_lib_src_page_sugars_ifequalbool_page_fair_js =
      'assets/fair/lib_src_page_sugars_ifequalbool_page.fair.js';

  static const String
      assets_fair_lib_src_page_sugars_ifequalbool_page_fair_json =
      'assets/fair/lib_src_page_sugars_ifequalbool_page.fair.json';

  static const String assets_fair_lib_src_page_sugars_ifrange_page_fair_bin =
      'assets/fair/lib_src_page_sugars_ifrange_page.fair.bin';

  static const String assets_fair_lib_src_page_sugars_ifrange_page_fair_js =
      'assets/fair/lib_src_page_sugars_ifrange_page.fair.js';

  static const String assets_fair_lib_src_page_sugars_ifrange_page_fair_json =
      'assets/fair/lib_src_page_sugars_ifrange_page.fair.json';

  static const String assets_fair_lib_src_page_sugars_map_page_fair_bin =
      'assets/fair/lib_src_page_sugars_map_page.fair.bin';

  static const String assets_fair_lib_src_page_sugars_map_page_fair_js =
      'assets/fair/lib_src_page_sugars_map_page.fair.js';

  static const String assets_fair_lib_src_page_sugars_map_page_fair_json =
      'assets/fair/lib_src_page_sugars_map_page.fair.json';

  static const String assets_fair_lib_src_page_sugars_mapeach_page_fair_bin =
      'assets/fair/lib_src_page_sugars_mapeach_page.fair.bin';

  static const String assets_fair_lib_src_page_sugars_mapeach_page_fair_js =
      'assets/fair/lib_src_page_sugars_mapeach_page.fair.js';

  static const String assets_fair_lib_src_page_sugars_mapeach_page_fair_json =
      'assets/fair/lib_src_page_sugars_mapeach_page.fair.json';

  static const String assets_fair_basic_config_json =
      'assets/fair_basic_config.json';

  /// {@macro assets_generator.assets_image_logo_png.preview}
  static const String assets_image_logo_png = 'assets/image/logo.png';

  /// {@macro assets_generator.assets_image_logo2_png.preview}
  static const String assets_image_logo2_png = 'assets/image/logo2.png';

  static const String assets_plugin_fair_common_plugin_js =
      'assets/plugin/fair_common_plugin.js';

  static const String assets_plugin_fair_plugins_js =
      'assets/plugin/fair_plugins.js';
}
