// This file is generated by Fair, do not edit manually!
// Updated on 2021-10-27 19:21:56.207621

String fairVersion = '3.0.0';
String flutterVersion = '3.0.5';
String dartVersion = '2.17.6';
int widgetCount = 358;
int apiCount = 212;
const widgetNames = {};
