// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// But you can define a new GeneratedModule as following:
// class MyAppGeneratedModule extends AppGeneratedModule {
//   @override
//   Map<String, dynamic> components() {
//     return <String, dynamic>{
//       ...super.components(),
//      // add your cases here.
//     };
//   }
//
//   /// true means it's a widget.
//   @override
//   Map<String, bool> mapping() {
//     return <String, bool>{
//       ...super.mapping(),
//       // remember add your cases here too.
//     };
//   }
// }
// **************************************************************************
// Auto generated by https://github.com/wuba/Fair
// **************************************************************************
//
// ignore_for_file: implementation_imports, unused_import, depend_on_referenced_packages, unused_shown_name, duplicate_import, always_specify_types, unnecessary_import

import 'package:flutter_slidable/flutter_slidable.dart';
import 'package:flutter_slidable/src/widgets/slidable.dart';
import 'package:flutter_slidable/src/widgets/slide_action.dart';
import 'package:flutter_slidable/src/widgets/slidable_action_pane.dart';
import 'package:flutter_slidable/src/widgets/slidable_dismissal.dart';
import 'package:flutter_slidable/src/widgets/fractionnally_aligned_sized_box.dart';
import 'dart:async';
import 'package:flutter/material.dart';
import 'package:flutter/widgets.dart';

import 'package:flutter/material.dart';
import 'package:fair/fair.dart';
import 'package:fair_version/fair_version.dart';

const Duration _kResizeDuration = Duration(milliseconds: 300);
const bool _kCloseOnTap = true;
const double _kActionsExtentRatio = 0.25;
const Duration _kMovementDuration = Duration(milliseconds: 200);

class AppGeneratedModule extends GeneratedModule {
  @override
  Map<String, dynamic> components() {
    return {
      'FractionallyAlignedSizedBox': (props) => FractionallyAlignedSizedBox(
            key: props['key'],
            child: props['child'],
            leftFactor: props['leftFactor']?.toDouble(),
            topFactor: props['topFactor']?.toDouble(),
            rightFactor: props['rightFactor']?.toDouble(),
            bottomFactor: props['bottomFactor']?.toDouble(),
            widthFactor: props['widthFactor']?.toDouble(),
            heightFactor: props['heightFactor']?.toDouble(),
          ),
      'SlidableStrechActionPane': (props) => SlidableStrechActionPane(
            key: props['key'],
          ),
      'SlidableBehindActionPane': (props) => SlidableBehindActionPane(
            key: props['key'],
          ),
      'SlidableScrollActionPane': (props) => SlidableScrollActionPane(
            key: props['key'],
          ),
      'SlidableDrawerActionPane': (props) => SlidableDrawerActionPane(
            key: props['key'],
          ),
      'SlidableDismissal': (props) => SlidableDismissal(
            key: props['key'],
            child: props['child'],
            dismissThresholds:
                props['dismissThresholds'] ?? const <SlideActionType, double>{},
            onResize: props['onResize'],
            onDismissed: props['onDismissed'],
            resizeDuration: props['resizeDuration'] ?? _kResizeDuration,
            crossAxisEndOffset: props['crossAxisEndOffset']?.toDouble() ?? 0.0,
            onWillDismiss: props['onWillDismiss'],
            closeOnCanceled: props['closeOnCanceled'] ?? false,
            dragDismissible: props['dragDismissible'] ?? true,
          ),
      'SlidableDrawerDismissal': (props) => SlidableDrawerDismissal(
            key: props['key'],
          ),
      'SlideAction': (props) => SlideAction(
            key: props['key'],
            child: props['child'],
            onTap: props['onTap'],
            color: props['color'],
            decoration: props['decoration'],
            closeOnTap: props['closeOnTap'] ?? _kCloseOnTap,
          ),
      'IconSlideAction': (props) => IconSlideAction(
            key: props['key'],
            icon: props['icon'],
            iconWidget: props['iconWidget'],
            caption: props['caption'],
            color: props['color'],
            foregroundColor: props['foregroundColor'],
            onTap: props['onTap'],
            closeOnTap: props['closeOnTap'] ?? _kCloseOnTap,
          ),
      'SlidableData': (props) => SlidableData(
            key: props['key'],
            actionType: props['actionType'],
            renderingMode: props['renderingMode'],
            totalActionsExtent: props['totalActionsExtent']?.toDouble() ?? 0,
            dismissThreshold: props['dismissThreshold']?.toDouble() ?? 0,
            dismissible: props['dismissible'],
            actionDelegate: props['actionDelegate'],
            overallMoveAnimation: props['overallMoveAnimation'],
            actionsMoveAnimation: props['actionsMoveAnimation'],
            dismissAnimation: props['dismissAnimation'],
            slidable: props['slidable'],
            actionExtentRatio: props['actionExtentRatio']?.toDouble() ?? 0,
            direction: props['direction'],
            child: props['child'],
          ),
      'SlidableData.of': (props) => SlidableData.of(
            props['pa'][0],
          ),
      'Slidable': (props) => Slidable(
            key: props['key'],
            child: props['child'],
            actionPane: props['actionPane'],
            actions: as<Widget>(props['actions']),
            secondaryActions: as<Widget>(props['secondaryActions']),
            showAllActionsThreshold:
                props['showAllActionsThreshold']?.toDouble() ?? 0.5,
            actionExtentRatio:
                props['actionExtentRatio']?.toDouble() ?? _kActionsExtentRatio,
            movementDuration: props['movementDuration'] ?? _kMovementDuration,
            direction: props['direction'] ?? Axis.horizontal,
            closeOnScroll: props['closeOnScroll'] ?? true,
            enabled: props['enabled'] ?? true,
            dismissal: props['dismissal'],
            controller: props['controller'],
            fastThreshold: props['fastThreshold']?.toDouble(),
          ),
      'Slidable.builder': (props) => Slidable.builder(
            key: props['key'],
            child: props['child'],
            actionPane: props['actionPane'],
            actionDelegate: props['actionDelegate'],
            secondaryActionDelegate: props['secondaryActionDelegate'],
            showAllActionsThreshold:
                props['showAllActionsThreshold']?.toDouble() ?? 0.5,
            actionExtentRatio:
                props['actionExtentRatio']?.toDouble() ?? _kActionsExtentRatio,
            movementDuration: props['movementDuration'] ?? _kMovementDuration,
            direction: props['direction'] ?? Axis.horizontal,
            closeOnScroll: props['closeOnScroll'] ?? true,
            enabled: props['enabled'] ?? true,
            dismissal: props['dismissal'],
            controller: props['controller'],
            fastThreshold: props['fastThreshold']?.toDouble(),
          ),
      'Slidable.of': (props) => Slidable.of(
            props['pa'][0],
          ),
      'SlidableRenderingMode': {
        'none': SlidableRenderingMode.none,
        'slide': SlidableRenderingMode.slide,
        'dismiss': SlidableRenderingMode.dismiss,
        'resize': SlidableRenderingMode.resize,
        'values': SlidableRenderingMode.values,
      },
      'SlideActionType': {
        'primary': SlideActionType.primary,
        'secondary': SlideActionType.secondary,
        'values': SlideActionType.values,
      },
    };
  }

  @override
  Map<String, bool> mapping() {
    return const {
      'FractionallyAlignedSizedBox': true,
      'SlidableStrechActionPane': true,
      'SlidableBehindActionPane': true,
      'SlidableScrollActionPane': true,
      'SlidableDrawerActionPane': true,
      'SlidableDismissal': true,
      'SlidableDrawerDismissal': true,
      'SlideAction': true,
      'IconSlideAction': true,
      'SlidableData': true,
      'Slidable': true,
      'SlidableRenderingMode': false,
      'SlideActionType': false,
    };
  }
}
