// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/assets_generator
// **************************************************************************
// ignore_for_file: constant_identifier_names

class Assets {
  const Assets._();
  static const String assets_fair_lib_src_page_complex_photo_gallery_fair_bin =
      'assets/fair/lib_src_page_complex_photo_gallery.fair.bin';

  static const String assets_fair_lib_src_page_complex_photo_gallery_fair_js =
      'assets/fair/lib_src_page_complex_photo_gallery.fair.js';

  static const String assets_fair_lib_src_page_complex_photo_gallery_fair_json =
      'assets/fair/lib_src_page_complex_photo_gallery.fair.json';

  static const String assets_fair_lib_src_page_complex_photo_gallery1_fair_bin =
      'assets/fair/lib_src_page_complex_photo_gallery1.fair.bin';

  static const String assets_fair_lib_src_page_complex_photo_gallery1_fair_js =
      'assets/fair/lib_src_page_complex_photo_gallery1.fair.js';

  static const String
      assets_fair_lib_src_page_complex_photo_gallery1_fair_json =
      'assets/fair/lib_src_page_complex_photo_gallery1.fair.json';

  static const String
      assets_fair_lib_src_page_complex_photo_gallery_item_fair_bin =
      'assets/fair/lib_src_page_complex_photo_gallery_item.fair.bin';

  static const String
      assets_fair_lib_src_page_complex_photo_gallery_item_fair_js =
      'assets/fair/lib_src_page_complex_photo_gallery_item.fair.js';

  static const String
      assets_fair_lib_src_page_complex_photo_gallery_item_fair_json =
      'assets/fair/lib_src_page_complex_photo_gallery_item.fair.json';

  static const String assets_fair_lib_src_page_complex_photo_swiper_fair_bin =
      'assets/fair/lib_src_page_complex_photo_swiper.fair.bin';

  static const String assets_fair_lib_src_page_complex_photo_swiper_fair_js =
      'assets/fair/lib_src_page_complex_photo_swiper.fair.js';

  static const String assets_fair_lib_src_page_complex_photo_swiper_fair_json =
      'assets/fair/lib_src_page_complex_photo_swiper.fair.json';

  static const String assets_fair_lib_src_page_simple_function_domain_fair_bin =
      'assets/fair/lib_src_page_simple_function_domain.fair.bin';

  static const String assets_fair_lib_src_page_simple_function_domain_fair_js =
      'assets/fair/lib_src_page_simple_function_domain.fair.js';

  static const String
      assets_fair_lib_src_page_simple_function_domain_fair_json =
      'assets/fair/lib_src_page_simple_function_domain.fair.json';

  static const String
      assets_fair_lib_src_page_simple_listenable_scope_fair_bin =
      'assets/fair/lib_src_page_simple_listenable_scope.fair.bin';

  static const String assets_fair_lib_src_page_simple_listenable_scope_fair_js =
      'assets/fair/lib_src_page_simple_listenable_scope.fair.js';

  static const String
      assets_fair_lib_src_page_simple_listenable_scope_fair_json =
      'assets/fair/lib_src_page_simple_listenable_scope.fair.json';

  static const String assets_fair_lib_src_page_simple_plugin_fair_bin =
      'assets/fair/lib_src_page_simple_plugin.fair.bin';

  static const String assets_fair_lib_src_page_simple_plugin_fair_js =
      'assets/fair/lib_src_page_simple_plugin.fair.js';

  static const String assets_fair_lib_src_page_simple_plugin_fair_json =
      'assets/fair/lib_src_page_simple_plugin.fair.json';

  static const String assets_fair_lib_src_page_simple_sugar_fair_bin =
      'assets/fair/lib_src_page_simple_sugar.fair.bin';

  static const String assets_fair_lib_src_page_simple_sugar_fair_js =
      'assets/fair/lib_src_page_simple_sugar.fair.js';

  static const String assets_fair_lib_src_page_simple_sugar_fair_json =
      'assets/fair/lib_src_page_simple_sugar.fair.json';

  static const String assets_fair_basic_config_json =
      'assets/fair_basic_config.json';

  /// {@macro assets_generator.assets_image_40_png.preview}
  static const String assets_image_40_png = 'assets/image/40.png';

  /// {@macro assets_generator.assets_image_avatar_jpg.preview}
  static const String assets_image_avatar_jpg = 'assets/image/avatar.jpg';

  /// {@macro assets_generator.assets_image_fluttercandies_grey_png.preview}
  static const String assets_image_fluttercandies_grey_png =
      'assets/image/flutterCandies_grey.png';

  /// {@macro assets_generator.assets_image_loading_gif.preview}
  static const String assets_image_loading_gif = 'assets/image/loading.gif';

  /// {@macro assets_generator.assets_image_love_png.preview}
  static const String assets_image_love_png = 'assets/image/love.png';

  /// {@macro assets_generator.assets_image_sun_glasses_png.preview}
  static const String assets_image_sun_glasses_png =
      'assets/image/sun_glasses.png';

  static const String assets_page_complex_photo_gallery_dart =
      'assets/page/complex/photo_gallery.dart';

  static const String assets_page_complex_photo_gallery1_dart =
      'assets/page/complex/photo_gallery1.dart';

  static const String assets_page_complex_photo_gallery_item_dart =
      'assets/page/complex/photo_gallery_item.dart';

  static const String assets_page_complex_photo_swiper_dart =
      'assets/page/complex/photo_swiper.dart';

  static const String assets_page_simple_function_domain_dart =
      'assets/page/simple/function_domain.dart';

  static const String assets_page_simple_listenable_scope_dart =
      'assets/page/simple/listenable_scope.dart';

  static const String assets_page_simple_plugin_dart =
      'assets/page/simple/plugin.dart';

  static const String assets_page_simple_sugar_dart =
      'assets/page/simple/sugar.dart';

  static const String assets_plugin_fair_common_plugin_js =
      'assets/plugin/fair_common_plugin.js';
}

final List<String> assetsArray = <String>[
  Assets.assets_fair_lib_src_page_complex_photo_gallery_fair_bin,
  Assets.assets_fair_lib_src_page_complex_photo_gallery_fair_js,
  Assets.assets_fair_lib_src_page_complex_photo_gallery_fair_json,
  Assets.assets_fair_lib_src_page_complex_photo_gallery1_fair_bin,
  Assets.assets_fair_lib_src_page_complex_photo_gallery1_fair_js,
  Assets.assets_fair_lib_src_page_complex_photo_gallery1_fair_json,
  Assets.assets_fair_lib_src_page_complex_photo_gallery_item_fair_bin,
  Assets.assets_fair_lib_src_page_complex_photo_gallery_item_fair_js,
  Assets.assets_fair_lib_src_page_complex_photo_gallery_item_fair_json,
  Assets.assets_fair_lib_src_page_complex_photo_swiper_fair_bin,
  Assets.assets_fair_lib_src_page_complex_photo_swiper_fair_js,
  Assets.assets_fair_lib_src_page_complex_photo_swiper_fair_json,
  Assets.assets_fair_lib_src_page_simple_function_domain_fair_bin,
  Assets.assets_fair_lib_src_page_simple_function_domain_fair_js,
  Assets.assets_fair_lib_src_page_simple_function_domain_fair_json,
  Assets.assets_fair_lib_src_page_simple_listenable_scope_fair_bin,
  Assets.assets_fair_lib_src_page_simple_listenable_scope_fair_js,
  Assets.assets_fair_lib_src_page_simple_listenable_scope_fair_json,
  Assets.assets_fair_lib_src_page_simple_plugin_fair_bin,
  Assets.assets_fair_lib_src_page_simple_plugin_fair_js,
  Assets.assets_fair_lib_src_page_simple_plugin_fair_json,
  Assets.assets_fair_lib_src_page_simple_sugar_fair_bin,
  Assets.assets_fair_lib_src_page_simple_sugar_fair_js,
  Assets.assets_fair_lib_src_page_simple_sugar_fair_json,
  Assets.assets_fair_basic_config_json,

  /// {@macro assets_generator.assets_image_40_png.preview}
  Assets.assets_image_40_png,

  /// {@macro assets_generator.assets_image_avatar_jpg.preview}
  Assets.assets_image_avatar_jpg,

  /// {@macro assets_generator.assets_image_fluttercandies_grey_png.preview}
  Assets.assets_image_fluttercandies_grey_png,

  /// {@macro assets_generator.assets_image_loading_gif.preview}
  Assets.assets_image_loading_gif,

  /// {@macro assets_generator.assets_image_love_png.preview}
  Assets.assets_image_love_png,

  /// {@macro assets_generator.assets_image_sun_glasses_png.preview}
  Assets.assets_image_sun_glasses_png,
  Assets.assets_page_complex_photo_gallery_dart,
  Assets.assets_page_complex_photo_gallery1_dart,
  Assets.assets_page_complex_photo_gallery_item_dart,
  Assets.assets_page_complex_photo_swiper_dart,
  Assets.assets_page_simple_function_domain_dart,
  Assets.assets_page_simple_listenable_scope_dart,
  Assets.assets_page_simple_plugin_dart,
  Assets.assets_page_simple_sugar_dart,
  Assets.assets_plugin_fair_common_plugin_js,
];
