// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/ff_annotation_route
// **************************************************************************
// fast mode: true
// version: 10.0.9
// **************************************************************************
// ignore_for_file: prefer_const_literals_to_create_immutables,unused_local_variable,unused_import,unnecessary_import,unused_shown_name,implementation_imports,duplicate_import
import 'package:fair_gallery/src/main_page.dart';
import 'package:fair_gallery/src/widget/extended_fair_widget.dart';
import 'package:flutter/foundation.dart';

/// The routeNames auto generated by https://github.com/fluttercandies/ff_annotation_route
const List<String> routeNames = <String>[
  'fair://DemoGroupPage',
  'fair://FunctionDomainDemo',
  'fair://ListenableScopeDemo',
  'fair://MainPage',
  'fair://PhotoGalleryItem',
  'fair://PhotoGalleryPage',
  'fair://PhotoGalleryPage1',
  'fair://PhotoSwiper',
  'fair://PluginDemo',
  'fair://SourceCodeViewPage',
  'fair://SugarDemo',
];

/// The routes auto generated by https://github.com/fluttercandies/ff_annotation_route
class Routes {
  const Routes._();

  /// 'DemoGroupPage'
  ///
  /// [name] : 'fair://DemoGroupPage'
  ///
  /// [routeName] : 'DemoGroupPage'
  ///
  /// [constructors] :
  ///
  /// DemoGroupPage : [MapEntry<String, List<DemoRouteResult>>(required) keyValue]
  ///
  /// [exts] : {'ffRouteFileImport': 'package:fair_gallery/src/main_page.dart'}
  static const _FairDemoGroupPage fairDemoGroupPage = _FairDemoGroupPage();

  /// 'Fair 支持的常用回调语法'
  ///
  /// [name] : 'fair://FunctionDomainDemo'
  ///
  /// [routeName] : 'Function 回调语法支持'
  ///
  /// [description] : 'Fair 支持的常用回调语法'
  ///
  /// [constructors] :
  ///
  /// FunctionDomainDemo : [Map<String, dynamic>(required) fairProps]
  ///
  /// [exts] : {ExtendedFairWidget.tag: true, 'group': '简单', 'order': 3, 'ffRouteFileImport': 'package:fair_gallery/src/page/simple/function_domain.dart'}
  static const _FairFunctionDomainDemo fairFunctionDomainDemo =
      _FairFunctionDomainDemo();

  /// '如何在 Fair 中使用 ScrollController, AnimationController, TabController, ValueNotifier'
  ///
  /// [name] : 'fair://ListenableScopeDemo'
  ///
  /// [routeName] : 'js 访问 Flutter 中对象的例子'
  ///
  /// [description] : '如何在 Fair 中使用 ScrollController, AnimationController, TabController, ValueNotifier'
  ///
  /// [exts] : {ExtendedFairWidget.tag: true, 'group': '简单', 'order': 4, 'ffRouteFileImport': 'package:fair_gallery/src/page/simple/listenable_scope.dart'}
  static const _FairListenableScopeDemo fairListenableScopeDemo =
      _FairListenableScopeDemo();

  /// 'MainPage'
  ///
  /// [name] : 'fair://MainPage'
  ///
  /// [routeName] : 'MainPage'
  ///
  /// [exts] : {'ffRouteFileImport': 'package:fair_gallery/src/main_page.dart'}
  static const _FairMainPage fairMainPage = _FairMainPage();

  /// 'PhotoGalleryItem'
  ///
  /// [name] : 'fair://PhotoGalleryItem'
  ///
  /// [routeName] : '图片列表单个元素'
  ///
  /// [description] : 'PhotoGalleryItem'
  ///
  /// [constructors] :
  ///
  /// PhotoGalleryItem : [Map<String, dynamic>(required) fairProps]
  ///
  /// [exts] : {ExtendedFairWidget.tag: true, 'ffRouteFileImport': 'package:fair_gallery/src/page/complex/photo_gallery_item.dart'}
  static const _FairPhotoGalleryItem fairPhotoGalleryItem =
      _FairPhotoGalleryItem();

  /// '展示如何使用Fair创建一个列表,使用 delegate 绑定 itemBuilder'
  ///
  /// [name] : 'fair://PhotoGalleryPage'
  ///
  /// [routeName] : '照片库列表'
  ///
  /// [description] : '展示如何使用Fair创建一个列表,使用 delegate 绑定 itemBuilder'
  ///
  /// [constructors] :
  ///
  /// PhotoGalleryPage : [Map<String, dynamic>(required) fairProps]
  ///
  /// [exts] : {ExtendedFairWidget.tag: true, 'group': '复杂', 'order': 0, 'ffRouteFileImport': 'package:fair_gallery/src/page/complex/photo_gallery.dart'}
  static const _FairPhotoGalleryPage fairPhotoGalleryPage =
      _FairPhotoGalleryPage();

  /// '展示如何使用Fair创建一个列表, 直接利用 FunctionDomain 创建 itemBuilder'
  ///
  /// [name] : 'fair://PhotoGalleryPage1'
  ///
  /// [routeName] : '照片库列表'
  ///
  /// [description] : '展示如何使用Fair创建一个列表, 直接利用 FunctionDomain 创建 itemBuilder'
  ///
  /// [constructors] :
  ///
  /// PhotoGalleryPage1 : [Map<String, dynamic>(required) fairProps]
  ///
  /// [exts] : {ExtendedFairWidget.tag: true, 'group': '复杂', 'order': 1, 'ffRouteFileImport': 'package:fair_gallery/src/page/complex/photo_gallery1.dart'}
  static const _FairPhotoGalleryPage1 fairPhotoGalleryPage1 =
      _FairPhotoGalleryPage1();

  /// '图片预览页面'
  ///
  /// [name] : 'fair://PhotoSwiper'
  ///
  /// [routeName] : 'PhotoSwiper'
  ///
  /// [description] : '图片预览页面'
  ///
  /// [constructors] :
  ///
  /// PhotoSwiper : [Map<String, dynamic>(required) fairProps]
  ///
  /// [pageRouteType] : PageRouteType.transparent
  ///
  /// [exts] : {ExtendedFairWidget.tag: true, 'ffRouteFileImport': 'package:fair_gallery/src/page/complex/photo_swiper.dart'}
  static const _FairPhotoSwiper fairPhotoSwiper = _FairPhotoSwiper();

  /// '通过 FairPlugin 在 js 中与 Flutter 交互'
  ///
  /// [name] : 'fair://PluginDemo'
  ///
  /// [routeName] : 'FairPlugin 示例'
  ///
  /// [description] : '通过 FairPlugin 在 js 中与 Flutter 交互'
  ///
  /// [exts] : {ExtendedFairWidget.tag: true, 'group': '简单', 'order': 2, 'ffRouteFileImport': 'package:fair_gallery/src/page/simple/plugin.dart'}
  static const _FairPluginDemo fairPluginDemo = _FairPluginDemo();

  /// 'SourceCodeViewPage'
  ///
  /// [name] : 'fair://SourceCodeViewPage'
  ///
  /// [routeName] : 'SourceCodeViewPage'
  ///
  /// [constructors] :
  ///
  /// SourceCodeViewPage : [String(required) asset]
  ///
  /// [exts] : {'ffRouteFileImport': 'package:fair_gallery/src/source_code_view_page.dart'}
  static const _FairSourceCodeViewPage fairSourceCodeViewPage =
      _FairSourceCodeViewPage();

  /// '常用语法糖例子'
  ///
  /// [name] : 'fair://SugarDemo'
  ///
  /// [routeName] : '语法糖例子'
  ///
  /// [description] : '常用语法糖例子'
  ///
  /// [constructors] :
  ///
  /// SugarDemo : [Map<String, dynamic>(required) fairProps]
  ///
  /// [exts] : {ExtendedFairWidget.tag: true, 'group': '简单', 'order': 1, 'ffRouteFileImport': 'package:fair_gallery/src/page/simple/sugar.dart'}
  static const _FairSugarDemo fairSugarDemo = _FairSugarDemo();
}

class _FairDemoGroupPage {
  const _FairDemoGroupPage();

  String get name => 'fair://DemoGroupPage';

  Map<String, dynamic> d({
    Key? key,
    required MapEntry<String, List<DemoRouteResult>> keyValue,
  }) =>
      <String, dynamic>{
        'key': key,
        'keyValue': keyValue,
      };

  @override
  String toString() => name;
}

class _FairFunctionDomainDemo {
  const _FairFunctionDomainDemo();

  String get name => 'fair://FunctionDomainDemo';

  Map<String, dynamic> d({
    Key? key,
    required Map<String, dynamic> fairProps,
  }) =>
      <String, dynamic>{
        'key': key,
        'fairProps': fairProps,
      };

  @override
  String toString() => name;
}

class _FairListenableScopeDemo {
  const _FairListenableScopeDemo();

  String get name => 'fair://ListenableScopeDemo';

  Map<String, dynamic> d({
    Key? key,
  }) =>
      <String, dynamic>{
        'key': key,
      };

  @override
  String toString() => name;
}

class _FairMainPage {
  const _FairMainPage();

  String get name => 'fair://MainPage';

  Map<String, dynamic> d({
    Key? key,
  }) =>
      <String, dynamic>{
        'key': key,
      };

  @override
  String toString() => name;
}

class _FairPhotoGalleryItem {
  const _FairPhotoGalleryItem();

  String get name => 'fair://PhotoGalleryItem';

  Map<String, dynamic> d({
    Key? key,
    required Map<String, dynamic> fairProps,
  }) =>
      <String, dynamic>{
        'key': key,
        'fairProps': fairProps,
      };

  @override
  String toString() => name;
}

class _FairPhotoGalleryPage {
  const _FairPhotoGalleryPage();

  String get name => 'fair://PhotoGalleryPage';

  Map<String, dynamic> d({
    Key? key,
    required Map<String, dynamic> fairProps,
  }) =>
      <String, dynamic>{
        'key': key,
        'fairProps': fairProps,
      };

  @override
  String toString() => name;
}

class _FairPhotoGalleryPage1 {
  const _FairPhotoGalleryPage1();

  String get name => 'fair://PhotoGalleryPage1';

  Map<String, dynamic> d({
    Key? key,
    required Map<String, dynamic> fairProps,
  }) =>
      <String, dynamic>{
        'key': key,
        'fairProps': fairProps,
      };

  @override
  String toString() => name;
}

class _FairPhotoSwiper {
  const _FairPhotoSwiper();

  String get name => 'fair://PhotoSwiper';

  Map<String, dynamic> d({
    Key? key,
    required Map<String, dynamic> fairProps,
  }) =>
      <String, dynamic>{
        'key': key,
        'fairProps': fairProps,
      };

  @override
  String toString() => name;
}

class _FairPluginDemo {
  const _FairPluginDemo();

  String get name => 'fair://PluginDemo';

  Map<String, dynamic> d({
    Key? key,
  }) =>
      <String, dynamic>{
        'key': key,
      };

  @override
  String toString() => name;
}

class _FairSourceCodeViewPage {
  const _FairSourceCodeViewPage();

  String get name => 'fair://SourceCodeViewPage';

  Map<String, dynamic> d({
    Key? key,
    required String asset,
  }) =>
      <String, dynamic>{
        'key': key,
        'asset': asset,
      };

  @override
  String toString() => name;
}

class _FairSugarDemo {
  const _FairSugarDemo();

  String get name => 'fair://SugarDemo';

  Map<String, dynamic> d({
    Key? key,
    required Map<String, dynamic> fairProps,
  }) =>
      <String, dynamic>{
        'key': key,
        'fairProps': fairProps,
      };

  @override
  String toString() => name;
}
