// Generated by Fair on 2022-05-31 13:02:55.553046.
import 'package:example/fair_widget/fairbinding/fair_binding_widget.dart';

import 'package:flutter/material.dart';
import 'package:fair/fair.dart';
import 'package:fair_version/fair_version.dart';

class AppGeneratedModule extends GeneratedModule {
  @override
  Map<String, dynamic> components() {
    return {
      'FairBindingWidget': (props) => FairBindingWidget(
            key: props['key'],
          ),
    };
  }

  @override
  Map<String, bool> mapping() {
    return const {
      'FairBindingWidget': true,
    };
  }
}
