// This file is generated by Fair, do not edit manually!

import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';

var p = () => {
      'BoxConstraints.lerp': (props) => BoxConstraints.lerp(
            props['pa'][0],
            props['pa'][1],
            props['pa'][2]?.toDouble(),
          ),
      'TableBorder.lerp': (props) => TableBorder.lerp(
            props['pa'][0],
            props['pa'][1],
            props['pa'][2]?.toDouble(),
          ),
      'WrapAlignment': {
        'values': WrapAlignment.values,
        'start': WrapAlignment.start,
        'end': WrapAlignment.end,
        'center': WrapAlignment.center,
        'spaceBetween': WrapAlignment.spaceBetween,
        'spaceAround': WrapAlignment.spaceAround,
        'spaceEvenly': WrapAlignment.spaceEvenly,
      },
      'WrapCrossAlignment': {
        'values': WrapCrossAlignment.values,
        'start': WrapCrossAlignment.start,
        'end': WrapCrossAlignment.end,
        'center': WrapCrossAlignment.center,
      },
      'HitTestBehavior': {
        'values': HitTestBehavior.values,
        'deferToChild': HitTestBehavior.deferToChild,
        'opaque': HitTestBehavior.opaque,
        'translucent': HitTestBehavior.translucent,
      },
      'DecorationPosition': {
        'values': DecorationPosition.values,
        'background': DecorationPosition.background,
        'foreground': DecorationPosition.foreground,
      },
      'ScrollDirection': {
        'values': ScrollDirection.values,
        'idle': ScrollDirection.idle,
        'forward': ScrollDirection.forward,
        'reverse': ScrollDirection.reverse,
      },
      'PaintingContext.repaintCompositedChild': (props) =>
          PaintingContext.repaintCompositedChild(
            props['pa'][0],
            debugAlsoPaintedParent: props['debugAlsoPaintedParent'] ?? false,
          ),
      'PaintingContext.debugInstrumentRepaintCompositedChild': (props) =>
          PaintingContext.debugInstrumentRepaintCompositedChild(
            props['pa'][0],
            debugAlsoPaintedParent: props['debugAlsoPaintedParent'] ?? false,
            customContext: props['customContext'],
          ),
      'FlexFit': {
        'values': FlexFit.values,
        'tight': FlexFit.tight,
        'loose': FlexFit.loose,
      },
      'MainAxisSize': {
        'values': MainAxisSize.values,
        'min': MainAxisSize.min,
        'max': MainAxisSize.max,
      },
      'MainAxisAlignment': {
        'values': MainAxisAlignment.values,
        'start': MainAxisAlignment.start,
        'end': MainAxisAlignment.end,
        'center': MainAxisAlignment.center,
        'spaceBetween': MainAxisAlignment.spaceBetween,
        'spaceAround': MainAxisAlignment.spaceAround,
        'spaceEvenly': MainAxisAlignment.spaceEvenly,
      },
      'CrossAxisAlignment': {
        'values': CrossAxisAlignment.values,
        'start': CrossAxisAlignment.start,
        'end': CrossAxisAlignment.end,
        'center': CrossAxisAlignment.center,
        'stretch': CrossAxisAlignment.stretch,
        'baseline': CrossAxisAlignment.baseline,
      },
      'TableCellVerticalAlignment': {
        'values': TableCellVerticalAlignment.values,
        'top': TableCellVerticalAlignment.top,
        'middle': TableCellVerticalAlignment.middle,
        'bottom': TableCellVerticalAlignment.bottom,
        'baseline': TableCellVerticalAlignment.baseline,
        'fill': TableCellVerticalAlignment.fill,
      },
      'ChildLayoutHelper.dryLayoutChild': (props) =>
          ChildLayoutHelper.dryLayoutChild(
            props['pa'][0],
            props['pa'][1],
          ),
      'ChildLayoutHelper.layoutChild': (props) => ChildLayoutHelper.layoutChild(
            props['pa'][0],
            props['pa'][1],
          ),
      'RenderViewport': {
        'useTwoPaneSemantics': RenderViewport.useTwoPaneSemantics,
        'excludeFromScrolling': RenderViewport.excludeFromScrolling,
      },
      'CacheExtentStyle': {
        'values': CacheExtentStyle.values,
        'pixel': CacheExtentStyle.pixel,
        'viewport': CacheExtentStyle.viewport,
      },
      'SliverGeometry': {
        'zero': SliverGeometry.zero,
      },
      'GrowthDirection': {
        'values': GrowthDirection.values,
        'forward': GrowthDirection.forward,
        'reverse': GrowthDirection.reverse,
      },
      'RelativeRect': {
        'fill': RelativeRect.fill,
      },
      'RelativeRect.lerp': (props) => RelativeRect.lerp(
            props['pa'][0],
            props['pa'][1],
            props['pa'][2]?.toDouble(),
          ),
      'RenderStack.getIntrinsicDimension': (props) =>
          RenderStack.getIntrinsicDimension(
            props['pa'][0],
            props['pa'][1],
          ),
      'RenderStack.layoutPositionedChild': (props) =>
          RenderStack.layoutPositionedChild(
            props['pa'][0],
            props['pa'][1],
            props['pa'][2],
            props['pa'][3],
          ),
      'StackFit': {
        'values': StackFit.values,
        'loose': StackFit.loose,
        'expand': StackFit.expand,
        'passthrough': StackFit.passthrough,
      },
      'SystemMouseCursors': {
        'none': SystemMouseCursors.none,
        'basic': SystemMouseCursors.basic,
        'click': SystemMouseCursors.click,
        'forbidden': SystemMouseCursors.forbidden,
        'wait': SystemMouseCursors.wait,
        'progress': SystemMouseCursors.progress,
        'contextMenu': SystemMouseCursors.contextMenu,
        'help': SystemMouseCursors.help,
        'text': SystemMouseCursors.text,
        'verticalText': SystemMouseCursors.verticalText,
        'cell': SystemMouseCursors.cell,
        'precise': SystemMouseCursors.precise,
        'move': SystemMouseCursors.move,
        'grab': SystemMouseCursors.grab,
        'grabbing': SystemMouseCursors.grabbing,
        'noDrop': SystemMouseCursors.noDrop,
        'alias': SystemMouseCursors.alias,
        'copy': SystemMouseCursors.copy,
        'disappearing': SystemMouseCursors.disappearing,
        'allScroll': SystemMouseCursors.allScroll,
        'resizeLeftRight': SystemMouseCursors.resizeLeftRight,
        'resizeUpDown': SystemMouseCursors.resizeUpDown,
        'resizeUpLeftDownRight': SystemMouseCursors.resizeUpLeftDownRight,
        'resizeUpRightDownLeft': SystemMouseCursors.resizeUpRightDownLeft,
        'resizeUp': SystemMouseCursors.resizeUp,
        'resizeDown': SystemMouseCursors.resizeDown,
        'resizeLeft': SystemMouseCursors.resizeLeft,
        'resizeRight': SystemMouseCursors.resizeRight,
        'resizeUpLeft': SystemMouseCursors.resizeUpLeft,
        'resizeUpRight': SystemMouseCursors.resizeUpRight,
        'resizeDownLeft': SystemMouseCursors.resizeDownLeft,
        'resizeDownRight': SystemMouseCursors.resizeDownRight,
        'resizeColumn': SystemMouseCursors.resizeColumn,
        'resizeRow': SystemMouseCursors.resizeRow,
        'zoomIn': SystemMouseCursors.zoomIn,
        'zoomOut': SystemMouseCursors.zoomOut,
      },
      'PlatformViewHitTestBehavior': {
        'values': PlatformViewHitTestBehavior.values,
        'opaque': PlatformViewHitTestBehavior.opaque,
        'translucent': PlatformViewHitTestBehavior.translucent,
        'transparent': PlatformViewHitTestBehavior.transparent,
      },
      'SelectionChangedCause': {
        'values': SelectionChangedCause.values,
        'tap': SelectionChangedCause.tap,
        'doubleTap': SelectionChangedCause.doubleTap,
        'longPress': SelectionChangedCause.longPress,
        'forcePress': SelectionChangedCause.forcePress,
        'keyboard': SelectionChangedCause.keyboard,
        'drag': SelectionChangedCause.drag,
      },
      'TextOverflow': {
        'values': TextOverflow.values,
        'clip': TextOverflow.clip,
        'fade': TextOverflow.fade,
        'ellipsis': TextOverflow.ellipsis,
        'visible': TextOverflow.visible,
      },
    };
