// This file is generated by Fair, do not edit manually!
// Updated on 2021-08-16 18:47:36.368714

import '\$\$c.dart' as $0;
import '\$\$w.dart' as $1;
import '\$\$p.dart' as $2;
import '\$\$m.dart' as $3;
import '\$\$r.dart' as $4;
import '\$\$a.dart' as $5;

mixin $BindingImpl {
  final provider = [
    $0.p,
    $1.p,
    $2.p,
    $3.p,
    $4.p,
    $5.p,
  ];
}
