// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/assets_generator
// **************************************************************************
// ignore_for_file: constant_identifier_names

class Assets {
  const Assets._();
  static const String assets_fair_lib_sugar_elseif_test_page_fair_bin =
      'assets/fair/lib_sugar_elseif_test_page.fair.bin';

  static const String assets_fair_lib_sugar_elseif_test_page_fair_js =
      'assets/fair/lib_sugar_elseif_test_page.fair.js';

  static const String assets_fair_lib_sugar_elseif_test_page_fair_json =
      'assets/fair/lib_sugar_elseif_test_page.fair.json';

  static const String assets_fair_lib_sugar_menu_fair_bin =
      'assets/fair/lib_sugar_menu.fair.bin';

  static const String assets_fair_lib_sugar_menu_fair_js =
      'assets/fair/lib_sugar_menu.fair.js';

  static const String assets_fair_lib_sugar_menu_fair_json =
      'assets/fair/lib_sugar_menu.fair.json';

  static const String assets_fair_lib_warp_demo_fair_bin =
      'assets/fair/lib_warp_demo.fair.bin';

  static const String assets_fair_lib_warp_demo_fair_js =
      'assets/fair/lib_warp_demo.fair.js';

  static const String assets_fair_lib_warp_demo_fair_json =
      'assets/fair/lib_warp_demo.fair.json';
}
