// Generated by Fair on 2021-06-24 19:09:41.179559.
import 'package:animated_text_kit/src/rotate.dart';

import 'package:flutter/material.dart';
import 'package:fair/fair.dart';
import 'package:fair_version/fair_version.dart';

class AppGeneratedModule extends GeneratedModule {
  @override
  Map<String, dynamic> components() {
    return {
      'RotateAnimatedTextKit': (props) => RotateAnimatedTextKit(
        key: props['key'],
        text: as<String>(props['text']) ?? [],
        textAlign: props['textAlign'] ??TextAlign.start,
        textStyle: props['textStyle'],
        transitionHeight: props['transitionHeight']?.toDouble(),
        alignment: props['alignment']??Alignment.center,
        textDirection: props['textDirection']??TextDirection.ltr,
        pause: props['pause'] ?? const Duration(milliseconds: 500),
        onNext: props['onNext'],
        onNextBeforePause: props['onNextBeforePause'],
        onFinished: props['onFinished'],
        totalRepeatCount: props['totalRepeatCount'] ?? 3,
        duration: props['duration'] ?? const Duration(milliseconds: 500),
        onTap: props['onTap'],
        displayFullTextOnTap: props['displayFullTextOnTap'] ?? false,
        repeatForever: props['repeatForever'] ?? false,
        isRepeatingAnimation: props['isRepeatingAnimation'] ?? true,
      ),
    };
  }

  @override
  Map<String, bool> mapping() {
    return const {
      'RotateAnimatedTextKit': true,
    };
  }
}
