// Generated by Fair on 2021-08-05 17:26:53.525113.
import 'package:animated_text_kit/src/rotate.dart';

import 'package:flutter/material.dart';
import 'package:fair/fair.dart';
import 'package:fair_version/fair_version.dart';

class AppGeneratedModule extends GeneratedModule {
  @override
  Map<String, dynamic> components() {
    return {
      'RotateAnimatedTextKit': (props) => RotateAnimatedTextKit(
            key: props['key'],
            text: List<String>.from(props['text']),
            textAlign: props['textAlign'] ?? TextAlign.start,
            textStyle: props['textStyle'],
            transitionHeight: props['transitionHeight']?.toDouble(),
            alignment: props['alignment'] ?? Alignment.center,
            textDirection: props['textDirection'] ?? TextDirection.ltr,
            duration: props['duration'] ?? const Duration(milliseconds: 2000),
            pause: props['pause'] ?? const Duration(milliseconds: 500),
            onTap: props['onTap'],
            onNext: props['onNext'],
            onNextBeforePause: props['onNextBeforePause'],
            onFinished: props['onFinished'],
            isRepeatingAnimation: props['isRepeatingAnimation'] ?? true,
            totalRepeatCount: props['totalRepeatCount'] ?? 3,
            repeatForever: props['repeatForever'] ?? false,
            displayFullTextOnTap: props['displayFullTextOnTap'] ?? false,
            stopPauseOnTap: props['stopPauseOnTap'] ?? false,
          ),
      'RotateAnimatedTextKit#onTap': (props) => () {
            return (props['block']);
          },
      'RotateAnimatedTextKit#onNext': (props) => (
            int,
            bool,
          ) {
            return (props['block']) as dynamic;
          },
      'RotateAnimatedTextKit#onNextBeforePause': (props) => (
            int,
            bool,
          ) {
            return (props['block']);
          },
      'RotateAnimatedTextKit#onFinished': (props) => () {
            return (props['block']);
          },
    };
  }

  @override
  Map<String, bool> mapping() {
    return const {
      'RotateAnimatedTextKit': true,
    };
  }
}
