// Generated by Fair on 2022-08-22 19:35:27.249265.

import 'package:flutter/material.dart';
import 'package:fair/fair.dart';
import 'package:fair_version/fair_version.dart';
import 'package:flutter_all_widgets/cupertinodatepicker/datepick_item.dart';

class AppGeneratedModule extends GeneratedModule {
  @override
  Map<String, dynamic> components() {
    return {
      'DatePickerItem': (props) => DatePickerItem(
            children: as<Widget>(props['children']),
          ),
    };
  }

  @override
  Map<String, bool> mapping() {
    return const {
      'DatePickerItem': true,
    };
  }
}
